name: build-artifacts

on:
  pull_request:
    branches: [ spritemaster ]
  push:
    branches: [ spritemaster ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: macintosh build
      working-directory: ./build/test
      run: |
        make build CC=clang EXTENSION=.dylib
    - name: upload macintosh artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./build/test/libzstd.dylib

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: linux build
      working-directory: ./build/test
      run: |
        make build CC=gcc EXTENSION=.so
    - name: upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./build/test/libzstd.so
        