name: build-artifacts

on:
  pull_request:
    branches: [ spritemaster ]
  push:
    branches: [ spritemaster ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
         ref: 'spritemaster'
    - name: macintosh build
      working-directory: ./build/test
      run: |
        make build CC=clang EXTENSION=.dylib; \
        ls -la
    - name: upload macintosh artifact
      uses: actions/upload-artifact@v3
      with:
        name: libzstd.dylib
        path: ./build/test/libzstd.dylib
        if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
         ref: 'spritemaster'
    - name: aptitude
      shell: bash
      run: |
        sudo apt update
        sudo apt install gcc-11 binutils -y
    - name: linux build
      working-directory: ./build/test
      shell: bash
      run: |
        make build CC=gcc-11 EXTENSION=.so; \
        ls -la
    - name: upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: libzstd.so
        path: ./build/test/libzstd.so
        if-no-files-found: error
        