name: build-artifacts

on:
  pull_request:
    branches: [ spritemaster ]
  push:
    branches: [ spritemaster ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
         ref: 'spritemaster'
    - name: macintosh build
      working-directory: ./build/makefile
      run: |
        export PATH="$(brew --prefix llvm@14)/bin:${PATH}"
        export LD="$(brew --prefix llvm@14)/bin/ld.lld"
        make shared CC=$(brew --prefix llvm@14)/bin/clang OUT_NAME=libzstd EXTENSION=.dylib
    - name: upload macintosh artifact
      uses: actions/upload-artifact@v3
      with:
        name: libzstd.dylib
        path: ./build/makefile/libzstd.dylib
        if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
         ref: 'spritemaster'
    - name: aptitude
      shell: bash
      run: |
        sudo apt update
        sudo apt install zsh make gcc-11 binutils -y
    - name: linux build
      working-directory: ./build/makefile
      shell: bash
      run: |
        make shared CC=gcc-11 OUT_NAME=libzstd EXTENSION=.so
    - name: upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: libzstd.so
        path: ./build/makefile/libzstd.so
        if-no-files-found: error
        